name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Set up Ko
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: go install github.com/google/ko@latest

      - name: Login with Ko
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ko login "ghcr.io" --username="chriswilding" --password="$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push with Ko
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ko publish . --bare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KO_DOCKER_REPO: "ghcr.io/chriswilding/crawl"
